modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "terrariamod"
version = "${version}"
displayName = "TerrariaMod"
authors = "Ryorama"
description = '''
A recreation of the popular game Terraria for Minecraft!
'''
logoFile = "icon.png"

[[dependencies.terrariamod]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrariamod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrariamod]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"