modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="Thanks to Re-Logic for making a great game!" #optional
authors="Ryorama" #optional

[[mods]] #mandatory
modId="terrariamod" #mandatory
version="0.1.0" #mandatory
displayName="Terrariamod" #mandatory
description='''
Terraria content in Minecraft!
'''

[[dependencies.terrariamod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.terrariamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
